name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Package Lambda function
        run: |
          cp -r src/. function
          cd function
          zip -r ../function.zip .
          cd ..

      - name: Deploy Lambda function
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ap-northeast-2
          function_name: crawling
          zip_file: function.zip
          environment: DB_HOST=${{ secrets.DB_HOST }},
            DB_USERNAME=${{ secrets.DB_USERNAME }},
            DB_PASSWORD=${{ secrets.DB_PASSWORD }},
            DB_NAME=${{ secrets.DB_NAME }},
            DB_PORT=${{ secrets.DB_PORT }}
